kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-pak-deployer-config
  namespace: {{ .Values.cp4d_namespace }}
data:
  cpd-config.yaml: >+
    ---

    global_config:
      environment_name: {{ .Values.cluster_name }}
      cloud_platform: existing-ocp

    openshift:

    - name: amt-cpd-dev
      ocp_version: 4.8
      cluster_name: {{ .Values.cluster_name }}
      domain_name: {{ .Values.cluster_ingress }}
      openshift_storage:
      - storage_name: ocs-storage
        storage_type: ocs
        ocs_storage_label: ocs
        ocs_storage_size_gb: 500

    cp4d:

    - project: cpd-instance
      openshift_cluster_name: {{ .Values.cluster_name }}
      cp4d_version: {{ .Values.cpd_version }}
      sequential_install: True
      accept_licenses: {{ .Values.license_accept }}
      cartridges:
      - name: cp-foundation
        license_service:
          state: disabled
          threads_per_core: 2
      - name: lite

    #

    # All tested cartridges. To install, change the "state" property to
    "installed". To uninstall, change the state

    # to "removed" or comment out the entire cartridge. Make sure that the "-"
    and properties are aligned with the lite

    # cartridge; the "-" is at position 3 and the property starts at position 5.

    #

      - name: analyticsengine 
        size: small 
        state: removed

      - name: bigsql
        state: removed

      - name: ca
        size: small
        instances:
        - name: ca-instance
          metastore_ref: ca-metastore
        state: removed

      - name: cde
        state: removed

      - name: datagate
        state: removed

      - name: datastage-ent-plus
        state: removed
        # instances:
        #   - name: ds-instance
        #     # Optional settings
        #     description: "datastage ds-instance"
        #     size: medium
        #     storage_class: efs-nfs-client
        #     storage_size_gb: 60
        #     # Custom Scale options
        #     scale_px_runtime:
        #       replicas: 2
        #       cpu_request: 500m
        #       cpu_limit: 2
        #       memory_request: 2Gi
        #       memory_limit: 4Gi
        #     scale_px_compute:
        #       replicas: 2
        #       cpu_request: 1
        #       cpu_limit: 3
        #       memory_request: 4Gi
        #       memory_limit: 12Gi    

      - name: db2
        size: small
        instances:
        - name: ca-metastore
          metadata_size_gb: 20
          data_size_gb: 20
          backup_size_gb: 20  
          transactionlog_size_gb: 20
        state: removed

      - name: db2u
        state: removed

      - name: db2wh
        state: removed

      - name: dmc
        state: removed

      - name: dods
        size: small
        state: removed

      - name: dp
        size: small
        state: removed

      - name: dv
        size: small 
        instances:
        - name: data-virtualization
        state: removed

      - name: hadoop
        size: small
        state: removed

      - name: mdm
        size: small
        wkc_enabled: true
        state: removed

      - name: openpages
        state: removed

      - name: planning-analytics
        state: removed

      - name: rstudio
        size: small
        state: removed

      - name: spss
        state: removed

      - name: voice-gateway
        replicas: 1
        state: removed

      - name: watson-assistant
        size: small
        state: removed

      - name: watson-discovery
        state: removed

      - name: watson-ks
        size: small
        state: removed

      - name: watson-openscale
        size: small
        state: removed

      - name: watson-speech
        stt_size: xsmall
        tts_size: xsmall
        state: removed

      - name: wkc
        size: small
        state: removed

      - name: wml
        size: small
        state: installed

      - name: wml-accelerator
        replicas: 1
        size: small
        state: removed

      - name: wsl
        state: installed

